### PR TITLE
[Deeplink] Added deeplink docu

### PR DESCRIPTION
**Pull request by palcalde**
Added deeplink docu to index.html

@arctarus @patriciagao  please review!

### CODE REVIEW

**Comment by patriciagao** [comment]
Can you add some screenshots please?? Is imposible to review that html!

**Comment by arctarus** [comment]
@palcalde just once think, please remove the section `Places` from the original file `doc/api/public.apib.md` and then generate your version. We don't want have that endpoints in the docs for now.

Thanks!

**Comment by palcalde** [comment]
@patriciagao I leave you a link to review this PR here: http://7693b6f4.ngrok.io
@arctarus sure, I'll remove it.

**Comment by palcalde** [comment]
Removed places!

**Comment by amuino** [comment]
A couple of things about style:

1. I'd start with an introductory section so that it shows on the sidebar.
2. I'd make more explicit that the links are for Cabify's Android and iOS mobile apps (not just Apps)

**Comment by amuino** [comment]
3. Sections for grouping related links would also be nice

**Comment by palcalde** [comment]
I've added an introductory section explaining better that is mobile deeplinking as suggested!

Merging this, thanks reviewers!

**Pull request merged**
